#ifndef FOCUS_CONFIG_H
#define FOCUS_CONFIG_H

#define FOCUS_CONFIG_MOTORS_NUM           1
#define FOCUS_CONFIG_SAMPLING_FREQUENCY   25000
#define FOCUS_CONFIG_FOC_BANDWIDTH        50.f
#define FOCUS_CONFIG_FOC_FF_BANDWIDTH     10.f
#define FOCUS_CONFIG_DEBUG_BUFFER_SAMPLES 500

#define FOCUS_CONFIG_MOTOR_POLE_PAIRS_NUM                   7
#define FOCUS_CONFIG_MOTOR_KV                               750
#define FOCUS_CONFIG_MOTOR_CALIBRATION_SAMPLES              10000
#define FOCUS_CONFIG_MOTOR_CALIBRATION_RESISTANCE_VOLTAGE   0.5f
#define FOCUS_CONFIG_MOTOR_CALIBRATION_INDUCTANCE_VOLTAGE   1.f
#define FOCUS_CONFIG_MOTOR_CALIBRATION_INDUCTANCE_FREQUENCY 1000.f
// #define FOCUS_CONFIG_MOTOR_CALIBRATION_KV_ENABLE
// #define FOCUS_CONFIG_MOTOR_CALIBRATION_KV_SETTLE  2.f
// #define FOCUS_CONFIG_MOTOR_CALIBRATION_KV_CURRENT 1.f

#define FOCUS_CONFIG_CURRENT_CALIBRATION_SAMPLES 1000
#define FOCUS_CONFIG_CURRENT_CALIBRATION_TIME    1.f
#define FOCUS_CONFIG_CURRENT_CALIBRATION_VOLTAGE 1.f

#define FOCUS_CONFIG_SENSORLESS_ENABLE
#define FOCUS_CONFIG_SENSORLESS_VELOCITY_MINIMAL   10.f
#define FOCUS_CONFIG_SENSORLESS_VELOCITY_TIME      2.f
#define FOCUS_CONFIG_SENSORLESS_VELOCITY_BANDWIDTH 50.f
#define FOCUS_CONFIG_SENSORLESS_ALIGN_TIME         0.25f
#define FOCUS_CONFIG_SENSORLESS_ALIGN_VOLTAGE      2.f
#define FOCUS_CONFIG_SENSORLESS_RAMP_TIME          1.f
#define FOCUS_CONFIG_SENSORLESS_RAMP_VOLTAGE       2.f
#define FOCUS_CONFIG_SENSORLESS_RAMP_LAMBDA        0.1f
#define FOCUS_CONFIG_SENSORLESS_RAMP_VELOCITY      200.f
#define FOCUS_CONFIG_SENSORLESS_SMO_G              0.5f
#define FOCUS_CONFIG_SENSORLESS_SMO_ETA            1.f

// #define FOCUS_CONFIG_ENCODER_ENABLE
// #define FOCUS_CONFIG_ENCODER_TYPE_AB
// #define FOCUS_CONFIG_ENCODER_TYPE_ABI
// #define FOCUS_CONFIG_ENCODER_TYPE_ABSOLUTE
// #define FOCUS_CONFIG_ENCODER_CPR                   4096
// #define FOCUS_CONFIG_ENCODER_VELOCITY_BANDWIDTH    50.f
// #define FOCUS_CONFIG_ENCODER_ALIGN_TIME            0.5f
// #define FOCUS_CONFIG_ENCODER_ALIGN_VOLTAGE         3.f
// #define FOCUS_CONFIG_ENCODER_INDEX_SEARCH_VELOCITY 10.f
// #define FOCUS_CONFIG_ENCODER_INDEX_SEARCH_VOLTAGE  3.f
// #define FOCUS_CONFIG_ENCODER_ECCENTRICITY_VELOCITY 2.f
// #define FOCUS_CONFIG_ENCODER_ECCENTRICITY_VOLTAGE  3.f
// #define FOCUS_CONFIG_ENCODER_ECCENTRICITY_ENABLE

#endif
